### ISSUE TITLE
[BUG] BUG AFTER I INSTAL VIA VERSION AND 1.13

### ISSUE THREAD

**Issue by LowScarlet** [SkyCraft78/DiSky#56]
**Name:** `MESSAGE FROM ID`
**Versions:** `1.13`

**Syntaxes affected:**
* Expression: `message from id`

**In-depth description of the bug:**
There is an error with a very long line that looks like a crash when I use the "via version" Plugin
The code is here:
https://pastebin.com/EnQSv5gZ

The error is here:
https://pastebin.com/4vVkysPc

**Comment by LowScarlet** [comment]
I did a test again, apparently the problem persists when I have removed the plugin via version, Previously I was using version 1.12, and this code worked fine

**Comment by LowScarlet** [comment]
On disky version 1.12 This code runs fine without "via version" plugin, When I add "via version" in disky 1.12 version the same error returns

**Comment by SkyCraft78** [comment]
I only forgot to handle the error, but this problem is normal.
As said in line 17 of your error paste (https://pastebin.com/4vVkysPc), the message you're trying to use/get simply doesn't exist.
ViaVersion or other plugins doesn't interfere at all with that error, as you can see in related classes (only DiSky classes are related)
