### ISSUE TITLE
[REQUEST] Callback for effects

### ISSUE THREAD

**Issue by vitusverden** [SkyCraft78/DiSky#7]
**Name:** `with callback:`

**Potential New Syntaxes:**
* Effect: Adding `[with callback:]` to the end of most, if not all effects

**Other syntaxes affected (if any):** `All effects`

**In-depth description of the new features:**

`Since every effect is async, it would be nice to have a callback. This would make things that require another effect (potentially an effect that takes a long time, fx logging in to bots) to be done be able to get executed after them.
I think it would be used, and I do personally also have a skript where it would be useful to have.`

`An example of the syntax in use could be:`
```
on load:
    broadcast "Logging in to {@botName}"
    register bot with token "{@botKey}" and with the name "{@botName}" with callback:
        broadcast "Logged in to {@botName}"
```

**Comment by SkyCraft78** [comment]
Hello,
I planning to add event waiter, but I don't wanna spoil currently :p
Anyway, I'll not add this type of syntaxes for multiple reason:
`•` I'll need to modify (again) the Skript parser, since there's no default way to do this.
`•` According to the parser's modification, the parsing of the code will be much longer.
`•` Finnally, this could be in conflit with the new feature i'm also planning.
Regards, Sky
